version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=backend_1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1955

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=backend_1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1955

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
